export type PromptCategory = { category: string; prompts: string[] };
export type PromptGroup = { id: string; title: string; note: string; categories: PromptCategory[] };

export const videoPromptGroups: PromptGroup[] = [
  {
    id: "thoi-trang-nu",
    title: "Video thời trang nữ (dọc 9:16)",
    note: "Prompt tiếng Việt, dùng cho video AI người mẫu nữ giới thiệu trang phục.",
    categories: [
      {
        category: "Nhân vật bước đi tự tin về phía trước",
        prompts: [
          "Tạo video dọc 9:16 từ bức ảnh tham chiếu. Cô gái bước đi tự tin với dáng người thẳng và nụ cười tự nhiên, sang trọng. Camera di chuyển mượt mà từ dưới lên, bắt trọn chi tiết trang phục và gương mặt. Giữ ánh sáng mềm mại, đồng đều, không bị chói trên khuôn mặt hay trang phục, đảm bảo màu sắc ổn định trong suốt chuyển động",
          "Tạo video 9:16 cô gái bước đi duyên dáng về phía camera. Cô giữ dáng người thẳng và nụ cười tự tin, thân thiện. Camera lia từ bước chân lên gương mặt. Đảm bảo ánh sáng đồng đều, không bị lóa hay nhấp nháy, giữ nguyên màu sắc và chất liệu vải khi cô di chuyển",
          "Tạo video dọc 9:16. Cô gái bước đi thanh lịch với nụ cười tự nhiên, thoải mái. Một tay thả tự nhiên theo bước đi, tay kia thả lỏng. Camera bắt đầu từ đôi chân và di chuyển lên khuôn mặt tự tin. Ánh sáng giữ mềm mại, ổn định, không bị chói hay thay đổi màu sắc bất thường",
          "Tạo video 9:16 cô gái bước đi đầy tự tin. Mái tóc khẽ bay khi cô bước, nụ cười tỏa sáng. Camera di chuyển mượt từ trang phục lên gương mặt. Giữ ánh sáng cân bằng, không bị lóe sáng hay làm mờ chi tiết trên quần áo và da.",
          "Tạo video dọc 9:16. Cô gái bước đi tự nhiên với dáng người thẳng, nụ cười tự tin, thanh lịch. Camera di chuyển mượt mà từ dưới lên, bắt trọn từng chi tiết trang phục. Giữ ánh sáng ổn định, không bị chói, màu sắc trang phục đồng bộ từ đầu đến cuối",
          "Tạo video 9:16 cô gái bước đi thoải mái và tự tin. Cô cười tự nhiên, dáng đi thanh lịch. Camera theo dõi từ bước chân lên khuôn mặt. Ánh sáng ổn định, mềm mại, không bị lóe sáng, giữ màu da và trang phục đồng nhất trong toàn bộ video.",
          "Tạo video 9:16. Cô gái bước đi mượt mà về phía camera với cử chỉ thoải mái và nụ cười tự tin. Camera di chuyển nhẹ nhàng từ dưới lên, làm nổi bật trang phục và khuôn mặt thanh lịch. Giữ ánh sáng đều, không bị lóa sáng hoặc thay đổi độ sáng đột ngột",
          "Tạo video dọc 9:16 cô gái bước đi tự tin về phía trước. Cô cười tự nhiên với phong thái sang trọng, điềm tĩnh. Camera lia từ phần thân dưới lên gương mặt, bắt trọn chi tiết trang phục và thần thái. Ánh sáng giữ ổn định, không méo màu, không bị sáng gắt",
          "Tạo video 9:16. Cô gái bước đi uyển chuyển, nụ cười nhẹ nhàng nhưng tự tin. Cử chỉ tự nhiên, thoải mái. Camera di chuyển mượt từ bước chân lên gương mặt. Giữ ánh sáng cân bằng và ổn định, không bị lóe sáng, màu sắc không thay đổi trong suốt cảnh quay.",
          "Tạo video dọc 9:16 từ bức ảnh tham chiếu. Cô gái bước đi với nụ cười bình tĩnh, thanh lịch, dáng người thẳng và duyên dáng. Camera di chuyển mượt từ bước chân lên gương mặt. Giữ ánh sáng mềm mại, ổn định, không bị chói, màu sắc trang phục đồng nhất từ đầu đến cuối",
          "Tạo video 9:16 trong đó cô gái bước vài bước thoải mái, tự tin. Một tay di chuyển tự nhiên theo nhịp bước, tay còn lại thả lỏng. Camera lia từ đôi chân lên gương mặt. Giữ ánh sáng cân bằng, không nhấp nháy hay lóa sáng, bảo toàn màu da và chi tiết vải tự nhiên",
          "Tạo video dọc 9:16 của cô gái bước đi duyên dáng với nụ cười thân thiện, tự nhiên. Chuyển động của cô mượt mà và tự tin. Camera bắt đầu từ phần thân dưới và di chuyển mượt lên gương mặt. Giữ ánh sáng mềm và đều, tránh hiệu ứng sáng bóng hay thay đổi màu sắc đột ngột.",
          "Tạo video 9:16. Cô gái bước đi tự nhiên với sự thanh lịch, nụ cười tự tin. Camera di chuyển đều từ chân lên đầu, làm nổi bật trang phục và biểu cảm. Ánh sáng cần duy trì đồng đều, mềm mại, không bị sáng gắt hay lóa bất thường.",
          "Tạo video dọc 9:16 của cô gái bước đi với phong thái tự tin, duyên dáng. Cô cười tự nhiên, bước đi thoải mái và mượt mà. Camera lướt nhẹ từ phần thân dưới lên gương mặt. Giữ khung cảnh đủ sáng với ánh sáng ổn định, mềm mại, tránh lóa sáng và đảm bảo màu sắc trang phục đồng nhất",
          "“Tạo video dọc 9:16 từ bức ảnh tham chiếu. Nhân vật bước đi tự tin, dáng người thẳng và nụ cười tự nhiên. Camera chuyển động mượt từ dưới lên, làm rõ chi tiết trang phục và gương mặt. Giữ ánh sáng mềm, đều, không chói và đảm bảo màu sắc ổn định trong suốt cảnh quay.”",
          "“Tạo video dọc 9:16 dựa trên ảnh tham chiếu. Cho nhân vật bước về phía trước đầy tự tin, nụ cười nhẹ nhàng, sang trọng. Camera lia từ chân lên mặt một cách mượt mà. Ánh sáng giữ mềm mại, không gắt, màu sắc ổn định trong toàn bộ chuyển động.”",
          "“Tạo video 9:16 từ ảnh tham chiếu. Nhân vật bước đi với phong thái tự tin, lưng thẳng và nụ cười tự nhiên. Camera di chuyển lên từ dưới, ghi lại rõ chất liệu trang phục và biểu cảm khuôn mặt. Ánh sáng phải mềm, đều và không thay đổi màu.”",
          "“Tạo video dọc 9:16. Nhân vật tiến về phía trước với dáng chuẩn và nụ cười tinh tế. Camera chạy mượt từ dưới lên, nhấn mạnh các chi tiết của outfit. Đảm bảo ánh sáng dịu, đồng đều, không lóe và màu sắc ổn định.”",
          "“Tạo video 9:16 từ ảnh tham chiếu. Nhân vật bước tự tin, giữ dáng thẳng và nụ cười tự nhiên. Camera quét từ dưới lên một cách liền mạch để bắt trọn outfit và gương mặt. Ánh sáng phải mềm và đều, không gây chói.”",
          "“Tạo video dọc 9:16. Nhân vật bước đi tao nhã, tự tin với nụ cười sang trọng. Camera nâng lên từ dưới, chuyển động mượt để làm rõ từng chi tiết trang phục. Ánh sáng giữ mềm, không gắt, màu sắc nhất quán.”",
          "“Tạo video 9:16 từ ảnh tham chiếu với nhân vật bước về phía trước đầy tự tin và nụ cười tự nhiên. Camera di chuyển từ dưới lên thật mượt, làm nổi bật outfit. Giữ ánh sáng dịu, đều và màu không bị thay đổi.”",
          "“Tạo video dọc 9:16. Nhân vật sải bước tự tin, dáng đứng thẳng và nụ cười nhẹ đầy tinh tế. Camera nâng dần từ dưới lên, bắt chi tiết trang phục và khuôn mặt. Ánh sáng phải mềm, đồng đều và không bị chói.”",
          "“Tạo video 9:16 từ hình tham chiếu. Nhân vật bước đi tự tin với tư thế chuẩn và biểu cảm tự nhiên. Camera từ chân lên mặt, di chuyển liền mạch để giữ outfit sắc nét. Đảm bảo ánh sáng dịu và màu sắc ổn định.”",
          "“Tạo video dọc 9:16. Nhân vật tiến về phía trước với sự tự tin, dáng người thẳng và nụ cười sang trọng. Camera mượt từ dưới lên, làm rõ chất liệu trang phục và gương mặt. Ánh sáng giữ mềm, đều, không chói và không đổi màu.”",
        ],
      },
      {
        category: "Vuốt tóc nhẹ nhàng",
        prompts: [
          "\"Tạo video dọc 9:16 từ ảnh tham chiếu. Cô gái mỉm cười tự nhiên, nhẹ nhàng đưa tay vuốt tóc từ trước ra sau. Gió thổi nhẹ làm tóc bay mềm mại. Camera bắt đầu ở phần trên cơ thể và zoom dần vào gương mặt để nhấn mạnh thần thái tươi sáng.\"",
          "\"Tạo video 9:16. Cô gái cười thanh lịch, một tay vuốt tóc qua vai một cách nhẹ nhàng. Gió nhẹ lướt qua làm mái tóc bay tự nhiên. Camera xoay chậm vòng quanh từ góc chéo trái lên phía trước, làm nổi bật sự mềm mại của tóc và chi tiết trang phục.\"",
          "\"Tạo video dọc 9:16. Cô gái mỉm cười ấm áp, tay phải khẽ vuốt tóc, mắt nhìn tự tin về phía trước. Gió thổi làm tóc tung bay nhẹ nhàng. Camera di chuyển từ dưới lên, bắt đầu từ bàn tay vuốt tóc đến khi zoom vào gương mặt tươi sáng.\"",
          "\"Tạo video 9:16. Cô gái vuốt tóc sang một bên trong khi mỉm cười duyên dáng. Gió thổi làm tóc bay nhẹ tự nhiên. Camera lia ngang từ trái sang phải, bắt trọn từng chi tiết chuyển động của bàn tay, mái tóc và nụ cười.\"",
          "\"Tạo video dọc 9:16. Cô gái vuốt nhẹ tóc từ bên tai xuống, gương mặt cười thân thiện. Gió nhẹ làm tóc bay mềm. Camera zoom chậm vào khuôn mặt và phần tóc đang được vuốt, giữ ánh sáng ổn định, không lóa, màu sắc trang phục đồng bộ.\"",
          "\"Tạo video 9:16. Cô gái bước chậm rãi về phía trước, một tay vuốt tóc nhẹ nhàng, cười thoải mái. Gió thổi tự nhiên làm tóc bay mềm mại. Camera theo dõi chuyển động từ toàn thân đến cận cảnh khuôn mặt, giữ chi tiết sản phẩm rõ ràng.\"",
          "\"Tạo video dọc 9:16. Cô gái cười tự nhiên, tay khẽ vuốt tóc ra sau vai. Gió làm tóc chuyển động mềm mại. Camera xoay vòng nhẹ 180 độ từ sau ra trước, bắt trọn cả thần thái tự tin và chuyển động mái tóc.\"",
          "\"Tạo video 9:16. Cô gái ngẩng mặt cười tươi, tay vuốt tóc từ trán sang bên. Gió thổi nhẹ làm tóc lay động. Camera di chuyển chậm từ phần ngực lên đến cận cảnh khuôn mặt, nhấn mạnh sự sang trọng và thoải mái.\"",
          "\"Tạo video dọc 9:16. Cô gái cười dịu dàng, một tay vuốt tóc mượt mà. Gió làm tóc bay tự nhiên quanh khuôn mặt. Camera tiến lại gần từ góc chéo dưới, nhấn mạnh chi tiết chất liệu áo và thần thái thân thiện.\"",
          "\"Tạo video 9:16. Cô gái vuốt tóc nhẹ nhàng và mỉm cười tự tin. Gió thổi khiến tóc bay mềm mại, tự nhiên. Camera lùi chậm từ cận cảnh khuôn mặt ra toàn thân, bắt trọn trang phục và thần thái sang trọng.\"",
          "\"Tạo video dọc 9:16. Cô gái nhẹ nhàng đưa tay vuốt tóc cùng với nụ cười tự nhiên, dịu dàng. Cơn gió nhẹ thổi qua, làm mái tóc bay mềm mại quanh vai. Camera từ từ zoom từ phần thân trên đến gương mặt, nhấn mạnh biểu cảm tươi sáng và chi tiết chất liệu trang phục.\"",
          "\"Tạo video dọc 9:16. Cô gái mỉm cười ấm áp khi vuốt tóc một cách duyên dáng. Gió thổi nhẹ, nâng vài lọn tóc bay tự nhiên. Camera nghiêng lên từ góc bên hông, làm nổi bật sự tinh tế của chất liệu trang phục và thần thái tự tin.\"",
          "\"Tạo video dọc 9:16. Cô gái mỉm cười nhẹ nhàng khi đưa tay vuốt tóc từ trước ra sau. Làn gió thoảng qua làm tóc bay quanh gương mặt. Camera di chuyển lại gần từ góc chéo hướng lên, tập trung cả vào thần thái thân thiện lẫn chất liệu vải mượt mà, sang trọng.\"",
          "\"Tạo video dọc 9:16. Với nụ cười tự nhiên và ánh mắt thư thái, cô gái chạm nhẹ vào tóc, để tóc rơi tự nhiên theo gió. Camera bắt đầu với khung cảnh rộng từ phần thân trên rồi tiến dần về phía gương mặt, làm nổi bật nét dịu dàng và chất liệu tinh tế của trang phục.\"",
          "\"Tạo video dọc 9:16. Cô gái mỉm cười thân thiện khi khẽ dùng tay vuốt tóc, trong khi gió thổi nhẹ làm tóc bay mềm mại. Camera tiến lại từ góc chéo thấp, bắt trọn gương mặt rạng rỡ và chi tiết chất liệu trang phục, đảm bảo không bị méo hoặc lóa sáng.\"",
        ],
      },
      {
        category: "Hành động Xoay người 360°",
        prompts: [
          "\"Tạo video dọc 9:16. Cô gái mỉm cười tự nhiên, xoay người chậm rãi 360°, dáng điệu thanh lịch. Camera lia theo vòng xoay, bắt trọn từng chi tiết bộ trang phục mà không làm biến dạng hay thay đổi màu sắc.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay người 360° một cách uyển chuyển, giữ dáng người thẳng và nụ cười dịu dàng. Camera di chuyển đồng bộ theo vòng xoay để nhấn mạnh từng góc độ của trang phục.\"",
          "\"Tạo video dọc 9:16. Cô gái bước nhẹ vài bước rồi xoay chậm 360°, mái tóc bay nhẹ trong gió. Camera lia mượt từ đầu đến chân, đảm bảo chi tiết trang phục giữ nguyên, không lỗi hay biến dạng.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay người chậm, một tay thả tự nhiên, một tay vuốt tóc. Camera quay vòng tròn theo, nhấn mạnh vẻ sang trọng và giữ nguyên chi tiết vải.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay trọn 360° với nụ cười tự tin. Camera bắt đầu từ góc thấp, lia dần lên theo vòng xoay, làm nổi bật toàn bộ thiết kế bộ trang phục.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay chậm 360°, giữ nhịp độ đều đặn để người xem thấy rõ mọi góc độ trang phục. Camera lia mượt, ánh sáng giữ ổn định, không chói.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay 360° trong không gian sang trọng, gương mặt tươi tắn. Camera di chuyển quanh cô gái, bắt trọn chi tiết trang phục từ nhiều góc khác nhau.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay chậm rãi một vòng 360°, dáng đứng thẳng, nụ cười thân thiện. Camera giữ khoảng cách hợp lý, lia theo mượt mà để tránh biến dạng sản phẩm.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay trọn vòng, tốc độ chậm, kết hợp nụ cười nhẹ nhàng. Camera từ từ zoom vào trang phục khi cô gái xoay, nhấn mạnh sự tinh tế của chất liệu.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay 360° duyên dáng, mái tóc nhẹ nhàng tung bay. Camera lia theo chuyển động, giữ đúng chi tiết và màu sắc của sản phẩm từ đầu đến cuối.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay người chậm rãi 360°, ánh mắt nhìn thẳng vào camera với nụ cười thân thiện. Camera lia trọn vòng, đảm bảo trang phục giữ nguyên thiết kế, không thay đổi.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay 360° trong tư thế thoải mái, một tay khẽ đặt bên hông. Camera lia đều theo vòng xoay, giữ ánh sáng tự nhiên và chi tiết sắc nét.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay chậm 360°, gương mặt toát lên sự tự tin. Camera bắt đầu từ góc chéo thấp rồi lia lên cao, nhấn mạnh thần thái sang trọng cùng trang phục.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay vòng 360°, nụ cười rạng rỡ. Camera lia chậm, zoom nhẹ vào những chi tiết quan trọng của bộ trang phục để thể hiện sự tinh tế.\"",
          "\"Tạo video dọc 9:16. Cô gái xoay nhẹ nhàng 360° trong không gian sáng dịu, dáng người thanh thoát. Camera lia trọn vòng xoay, giữ chi tiết sắc nét, không bị chói hay lỗi sản phẩm.\"",
        ],
      },
      {
        category: "Chỉnh cổ áo / tay áo",
        prompts: [
          "\"Tạo video dọc 9:16. Cô gái mỉm cười sang trọng, dùng một tay chỉnh nhẹ cổ áo. Camera zoom cận vào phần cổ áo để làm nổi bật chi tiết may và chất liệu, ánh sáng mềm mại, không bị chói.\"",
          "\"Tạo video dọc 9:16. Cô gái đưa tay khẽ chỉnh cổ áo, biểu cảm tự tin và duyên dáng. Camera lia từ gương mặt xuống cổ áo, giữ rõ chi tiết từng đường vải, không biến dạng.\"",
          "\"Tạo video dọc 9:16. Một tay cô gái nhẹ nhàng chỉnh phần cổ áo trong khi tay kia thả tự nhiên. Camera di chuyển cận cảnh cổ áo và vải áo, ánh sáng ổn định, màu sắc đồng nhất.\"",
          "\"Tạo video dọc 9:16. Cô gái cười nhẹ, tay vuốt nhẹ cổ áo như chỉnh cho ngay ngắn. Camera từ góc chéo tiến lại gần cổ áo, nhấn mạnh chất liệu mềm mại, giữ nguyên màu sắc chuẩn.\"",
          "\"Tạo video dọc 9:16. Cô gái dùng tay chỉnh lại cổ áo, dáng vẻ sang trọng. Camera zoom dần từ toàn thân vào phần cổ áo, bắt chi tiết vải không bị lỗi hay biến dạng.\"",
          "\"Tạo video dọc 9:16. Cô gái chỉnh cổ áo bằng động tác chậm rãi, mượt mà. Camera lia ngang từ trái sang phải, bắt cận phần cổ áo và chất liệu, ánh sáng tự nhiên.\"",
          "\"Tạo video dọc 9:16. Cô gái cười tự nhiên, đưa tay chỉnh cổ áo như một hành động tinh tế. Camera xoay nhẹ 180° quanh cô gái, nhưng luôn giữ rõ chi tiết phần cổ áo và màu sắc không thay đổi.\"",
          "\"Tạo video dọc 9:16. Cô gái chỉnh lại tay áo, động tác dứt khoát nhưng sang trọng. Camera zoom vào phần tay áo, nhấn mạnh độ co giãn và form ôm vừa vặn.\"",
          "\"Tạo video dọc 9:16. Một tay cô gái chỉnh lại khuyết tay áo, nụ cười tự tin. Camera bắt đầu từ bàn tay rồi di chuyển lên gương mặt, đồng bộ màu sắc và ánh sáng.\"",
          "\"Tạo video dọc 9:16. Cô gái đưa tay kéo nhẹ phần tay áo, biểu cảm thoải mái. Camera di chuyển cận cảnh từ tay áo lên vai, giữ nguyên chi tiết chất liệu vải.\"",
          "\"Tạo video dọc 9:16. Cô gái khẽ chỉnh tay áo bằng cử chỉ tự nhiên, nụ cười nhẹ nhàng. Camera zoom chậm vào phần tay áo, không làm méo form hoặc thay đổi chi tiết.\"",
          "\"Tạo video dọc 9:16. Cô gái chỉnh cổ áo rồi mỉm cười, ánh mắt tự tin. Camera bắt trọn khoảnh khắc từ xa đến gần, giữ đúng màu vải và chi tiết từng đường may.\"",
          "\"Tạo video dọc 9:16. Cô gái vừa cười vừa khẽ chỉnh lại cổ áo. Camera lia từ góc dưới lên, tập trung vào cổ áo và thần thái sang trọng của gương mặt.\"",
          "\"Tạo video dọc 9:16. Cô gái chỉnh tay áo rồi xoay nhẹ người để tạo điểm nhấn. Camera zoom vào chi tiết tay áo trong quá trình chuyển động, giữ ổn định màu sắc.\"",
          "\"Tạo video dọc 9:16. Cô gái mỉm cười, khẽ vuốt và chỉnh cổ áo để tạo sự chỉnh chu. Camera quay cận cảnh từ nhiều góc, làm nổi bật chất liệu vải mượt mà, không bị lóa sáng.\"",
        ],
      },
      {
        category: "Cầm túi xách nhưng nhấn mạnh trang phục",
        prompts: [
          "Tạo video dọc 9:16. Cô gái mỉm cười nhẹ nhàng, tay cầm túi thả lỏng tự nhiên. Camera bắt đầu từ túi, lia lên toàn thân, nhấn mạnh bộ quần áo gọn gàng và màu sắc chân thực.",
          "Cô gái bước đi chậm rãi, tay cầm túi uyển chuyển theo nhịp. Camera lia từ túi lên toàn thân, giữ rõ đường nét của áo và váy – bộ trang phục là điểm nhấn chính.",
          "Tạo video dọc. Cô gái đứng yên, tay cầm túi nhẹ trước người. Camera zoom vào túi trong vài giây rồi di chuyển lên toàn thân, làm nổi bật chi tiết áo và váy sang trọng.",
          "Cô gái xoay nhẹ người sang bên, tay vẫn cầm túi. Camera lia mượt mà từ dưới lên, đảm bảo ánh sáng làm nổi bật vải áo và phom dáng trang phục.",
          "Tạo video. Cô gái cười thân thiện, bước một bước về phía trước. Camera tracking theo chuyển động, bắt đầu từ túi rồi nhấn mạnh bộ quần áo thanh lịch.",
          "Cô gái chỉnh nhẹ quai túi bằng một tay, nụ cười tự tin. Camera cận túi trong thoáng chốc rồi lia chậm lên khuôn mặt, đảm bảo bộ trang phục rõ nét, không bị biến dạng.",
          "Tạo video. Cô gái đưa túi ra phía trước bụng, cử chỉ thoải mái. Camera lia từ túi lên toàn thân, giữ chi tiết mượt mà của áo và váy, trang phục nổi bật hơn túi.",
          "Cô gái đứng nghiêng, tay cầm túi sát bên người, dáng tự nhiên. Camera lia chậm từ túi sang toàn thân, nhấn mạnh sự mềm mại của vải áo và váy.",
          "Tạo video dọc. Cô gái bước đi trong không gian sang trọng, túi cầm nhẹ theo nhịp bước. Camera lia từ dưới lên, lấy rõ chi tiết trang phục làm trung tâm.",
          "Cô gái mỉm cười thân thiện, tay cầm túi đưa hơi nghiêng sang bên. Camera quay cận túi trong thoáng chốc rồi di chuyển lên áo và váy – trang phục là chủ thể chính.",
          "Tạo video. Cô gái xoay chậm 360°, tay vẫn cầm túi uyển chuyển. Camera lia theo vòng xoay, nhấn mạnh sự mềm mại và form chuẩn của bộ quần áo.",
          "Cô gái đặt nhẹ túi sang một bên khi đứng, dáng thẳng tự tin. Camera bắt đầu từ túi, lia chậm lên toàn thân, làm nổi bật chất liệu áo và váy.",
          "Tạo video. Cô gái bước vài bước ngắn, túi cầm trong tay. Camera lia tracking theo nhịp bước, nhưng tập trung nhấn mạnh thần thái tự tin và bộ trang phục.",
          "Cô gái cười rạng rỡ, túi cầm thoải mái trong tay. Camera lia từ dưới lên, bắt đầu ở túi rồi zoom vào áo và váy, đảm bảo màu sắc đồng bộ và trung thực.",
          "Tạo video dọc 9:16. Cô gái đứng tự nhiên, một tay cầm túi, dáng người thanh thoát. Camera lia từ túi lên toàn thân, giữ quần áo rõ ràng, là điểm nhấn chủ đạo.",
        ],
      },
      {
        category: "Kéo giãn áo (ống tay/eo)",
        prompts: [
          "\"Tạo video dọc 9:16. Cô gái mỉm cười tự nhiên, dùng hai tay kéo nhẹ phần ống tay áo để thể hiện độ co giãn. Camera zoom cận vào phần tay áo, ánh sáng ổn định, màu sắc vải giữ nguyên, không bị biến dạng.\"",
          "\"Tạo video dọc 9:16. Một tay cô gái giữ cố định, tay kia kéo nhẹ phần eo áo để làm nổi bật khả năng co giãn. Camera di chuyển từ góc chéo cận chi tiết vải, đảm bảo giữ đúng màu sắc và chất liệu.\"",
          "\"Tạo video dọc 9:16. Cô gái vừa mỉm cười vừa dùng hai tay kéo giãn phần áo ở trước ngực. Camera từ từ zoom vào khu vực đang kéo để nhấn mạnh độ đàn hồi tự nhiên của vải.\"",
          "\"Tạo video dọc 9:16. Cô gái nhẹ nhàng kéo giãn ống tay áo sang hai bên. Camera bắt đầu từ toàn thân rồi zoom cận vào phần tay áo, giữ rõ chi tiết từng đường vải.\"",
          "\"Tạo video dọc 9:16. Cô gái đặt hai tay vào phần hông áo, kéo sang hai bên để minh họa độ co giãn. Camera lia theo động tác, nhấn mạnh sự mềm mại và thoải mái của chất liệu.\"",
          "\"Tạo video dọc 9:16. Cô gái khẽ kéo giãn áo ở phần bụng trong khi cười nhẹ nhàng. Camera zoom chậm vào chi tiết vải, đảm bảo ánh sáng đều và không bị lóa.\"",
          "\"Tạo video dọc 9:16. Một tay cô gái kéo ống tay áo ra ngoài, tay kia giữ cố định. Camera di chuyển mượt từ khuôn mặt xuống phần áo, bắt trọn cả thần thái và chi tiết vải.\"",
          "\"Tạo video dọc 9:16. Cô gái kéo giãn áo ở eo theo chiều ngang, nụ cười tươi tắn. Camera cận chi tiết vải, đảm bảo thấy rõ sự đàn hồi mà không thay đổi thiết kế áo.\"",
          "\"Tạo video dọc 9:16. Cô gái dùng cả hai tay kéo giãn áo về hai phía. Camera zoom chậm vào, giữ chi tiết rõ ràng và màu sắc đồng bộ.\"",
          "\"Tạo video dọc 9:16. Cô gái đứng thẳng, vừa cười vừa kéo giãn phần áo ở hông. Camera lia cận từ góc chéo thấp để bắt trọn sự uyển chuyển và chi tiết sản phẩm.\"",
          "\"Tạo video dọc 9:16. Một tay kéo phần vải áo ở bụng, tay còn lại vuốt nhẹ để cho thấy sự co giãn. Camera di chuyển theo tay, giữ rõ chất liệu.\"",
          "\"Tạo video dọc 9:16. Cô gái kéo giãn áo theo chiều dọc từ eo xuống. Camera zoom từ xa đến gần, nhấn mạnh sự đàn hồi mà không biến dạng form áo.\"",
          "\"Tạo video dọc 9:16. Cô gái kéo giãn phần tay áo rồi buông nhẹ để áo trở lại trạng thái ban đầu. Camera quay chậm động tác, giữ đúng chi tiết và màu sắc.\"",
          "\"Tạo video dọc 9:16. Cô gái vừa mỉm cười vừa kéo giãn áo nhẹ nhàng. Camera xoay chậm từ trái qua phải, bắt trọn thần thái tự tin và chi tiết vải.\"",
          "\"Tạo video dọc 9:16. Cô gái dùng tay kéo áo ra hai bên, ánh mắt nhìn xuống chi tiết vải với nụ cười thân thiện. Camera zoom cận để làm rõ sự co giãn tự nhiên và bề mặt vải.\"",
        ],
      },
      {
        category: "Hành động Chỉ tay vào sản phẩm",
        prompts: [
          "Tạo video dọc 9:16. Cô gái mỉm cười nhẹ, dùng một tay chỉ vào logo trên áo. Camera zoom cận logo rồi từ từ lùi ra toàn thân, ánh sáng mềm mại và ổn định.",
          "Tạo video dọc 9:16. Cô gái nghiêng nhẹ người, tay phải chỉ vào họa tiết áo, mắt nhìn theo hướng tay chỉ. Camera lia theo từ bàn tay đến khuôn mặt tươi tắn.",
          "Tạo video dọc 9:16. Cô gái dùng một tay chỉ vào phần giá sản phẩm trên bảng nhỏ cầm bên cạnh. Camera cận cảnh theo hướng chỉ, sau đó lướt lên toàn bộ outfit.",
          "Tạo video dọc 9:16. Cô gái chỉ tay vào vải áo ở phần ngực, nụ cười thân thiện. Camera zoom chậm để làm rõ chất liệu, màu sắc chính xác.",
          "Tạo video dọc 9:16. Cô gái khẽ đưa tay chỉ vào viền cổ áo, mắt nhìn camera, cười tự tin. Camera xoay nhẹ từ trái sang phải, nhấn chi tiết vải.",
          "Tạo video dọc 9:16. Cô gái đưa tay chỉ vào tay áo để làm nổi bật độ co giãn. Camera zoom cận, ánh sáng đều, màu vải giữ tự nhiên.",
          "Tạo video dọc 9:16. Cô gái đứng thẳng, chỉ tay vào phần túi xách đang cầm. Camera lia từ túi lên toàn bộ bộ trang phục, nhấn mạnh tính sang trọng.",
          "Tạo video dọc 9:16. Cô gái dùng tay chỉ vào phần eo áo, gương mặt cười dịu dàng. Camera zoom cận chi tiết, đảm bảo vải không bị méo.",
          "Tạo video dọc 9:16. Cô gái chỉ tay vào họa tiết nhỏ trên vạt áo, mắt hướng theo tay. Camera cận cảnh rồi kéo focus ra toàn thân.",
          "Tạo video dọc 9:16. Cô gái đưa tay chỉ vào phần cúc áo, cười nhẹ. Camera bắt đầu từ bàn tay rồi di chuyển dần lên khuôn mặt.",
          "Tạo video dọc 9:16. Cô gái chỉ vào phần đường may tinh tế ở áo, tay giữ nhẹ nhàng. Camera lia chậm theo chiều dọc đường may.",
          "Tạo video dọc 9:16. Cô gái khẽ chỉ vào tag giá trên áo, cười thoải mái. Camera zoom cận thẻ giá và chất vải xung quanh.",
          "Tạo video dọc 9:16. Cô gái dùng một tay chỉ vào chi tiết gấu áo, mắt nhìn trực diện vào camera. Camera lia từ chi tiết gấu áo lên nụ cười tự nhiên.",
          "Tạo video dọc 9:16. Cô gái dùng tay chỉ vào chi tiết đặc biệt (logo nhỏ trên ngực). Camera cận chi tiết rồi xoay nhẹ 180° để thấy tổng thể.",
          "Tạo video dọc 9:16. Cô gái cười tươi, dùng tay chỉ vào áo và kết hợp gật nhẹ đầu. Camera tracking theo hướng tay chỉ để làm nổi bật sản phẩm.",
        ],
      },
      {
        category: "Đi về phía camera – bước gần lại với sự tự tin",
        prompts: [
          "Tạo video dọc 9:16. Cô gái bước chậm rãi về phía camera, nụ cười sang trọng và tự tin. Camera hơi rung nhẹ để tạo cảm giác gần gũi, ánh sáng ổn định giữ nguyên chi tiết và màu sắc trang phục.",
          "Video dọc 9:16. Nhân vật tiến gần lại camera từng bước uyển chuyển, dáng người thẳng, nụ cười thân thiện. Camera tracking theo chuyển động, hơi rung tự nhiên để làm tăng tính chân thực.",
          "Tạo video dọc 9:16. Cô gái bước thoải mái về phía camera, ánh mắt nhìn trực diện. Camera di chuyển lùi nhẹ để giữ khung hình cân đối, màu sắc áo và váy không thay đổi trong suốt quá trình quay.",
          "Video 9:16. Cô gái tiến về phía trước với nụ cười tự nhiên, dáng đi thanh lịch. Camera rung nhè nhẹ tạo cảm giác gần gũi, bắt trọn chi tiết bộ quần áo mà không bị biến dạng.",
          "Tạo video dọc 9:16. Nhân vật bước lại gần camera, gương mặt sáng, nụ cười sang trọng. Camera zoom nhẹ theo bước đi, ánh sáng mềm mại giữ màu sắc tự nhiên của vải áo.",
          "Video 9:16. Cô gái đi một cách thoải mái, tự tin tiến lại gần camera. Camera rung vừa đủ để tạo cảm giác chân thật như đang tiếp cận người xem, nhấn mạnh chi tiết chất liệu sản phẩm.",
          "Tạo video dọc 9:16. Nhân vật tiến thẳng về phía camera, một tay đưa túi xách nhẹ nhàng. Camera lia từ dưới chân lên gương mặt, đảm bảo ánh sáng đồng đều không bị chói.",
          "Video dọc 9:16. Cô gái bước từng bước ngắn nhưng chắc chắn về phía camera, mái tóc khẽ bay tự nhiên. Camera tracking mượt, kết hợp rung nhẹ để tăng cảm giác thực tế.",
          "Tạo video dọc 9:16. Nhân vật mỉm cười khi tiến lại gần camera, động tác tay thả lỏng theo bước đi. Camera zoom dần vào trang phục, nhấn mạnh sự tinh tế của chất liệu.",
          "Video 9:16. Cô gái bước đến gần camera với ánh mắt tự tin, nụ cười tự nhiên. Camera rung nhẹ như góc nhìn thật của người quan sát, giữ nguyên màu sắc và chi tiết sản phẩm.",
          "Tạo video dọc 9:16. Nhân vật tiến lại gần camera từng bước mềm mại, dáng đi thanh lịch. Camera rung tự nhiên, bắt trọn ánh sáng đồng đều từ đầu đến cuối video.",
          "Tạo video dọc 9:16. Nhân vật di chuyển về phía camera với nụ cười dịu dàng. Camera giữ góc trung bình, rung nhẹ tạo cảm giác chân thật như đang ở gần.",
          "Video 9:16. Cô gái tiến gần lại camera, bước đi mượt mà và dứt khoát. Camera zoom chậm, bắt trọn chi tiết áo và váy, không làm thay đổi màu sắc sản phẩm.",
          "eo dọc 9:16. Nhân vật tiến vTạo vidề phía camera, nụ cười toả sáng. Camera rung tự nhiên như hơi thở của người cầm máy, kết hợp ánh sáng mềm để làm rõ thần thái tự tin.",
        ],
      },
      {
        category: "Chuyển động đi thẳng và xoay vòng",
        prompts: [
          "A stylish young woman walks gracefully through an outdoor café street. She moves slowly and elegantly, with soft, natural body motion. Her steps are light; her hips sway gently; the skirt flows and sways with each step; the top fabric moves subtly with the wind. She stops, turns her body slowly to the left, then does a smooth 360-degree spin to show the entire outfit. The skirt’s hem sways softly outward during the spin, showing the fabric texture clearly. Her hair moves lightly with her motion, and her arms make small natural gestures—relaxed, feminine, elegant. Camera follows her from the front, then slightly to the side, then circles around her as she turns, keeping the outfit in focus. Soft café background, people blurred, warm daylight, high fashion look. Motion must be smooth, light, natural, no stiff movement.”",
          "Từ ảnh tham chiếu về chai sịt vải tạo câu lệnh tiếng việt để trông nó như một sp ri viu quảng cáo chuyên nghiệp trên Tivi có bối cảnh , có người dùng và sản phẩm, có thuyết minh về sản phẩm và là video dọc 9:16 độ dài của video là 8 giây. Yêu cầu độ chuyên nghiệp và sắc nết cao. Camera đi chuyển chuyên nghiệp",
          "Một cô gái trẻ ngồi tại bàn làm việc ấm áp cạnh cửa sổ, ánh sáng tự nhiên ban ngày dịu nhẹ. Nhân vật cầm một chiếc túi xách màu be bằng hai tay, nhẹ nhàng nâng túi lên để quan sát. Camera bắt đầu từ góc rộng phía sau vai nhân vật, sau đó di chuyển chậm rãi từ xa vào gần, tiến dần về phía chiếc túi. Camera lấy nét rõ vào túi, làm mờ nhẹ khuôn mặt và hậu cảnh. Chuyển động tay tự nhiên, túi xoay nhẹ để lộ form dáng, chất liệu và dây buộc. Phong cách quay video review thời trang cao cấp, chuyển động mượt, ổn định, ánh sáng mềm, hình ảnh sắc nét, chân thực, cảm giác như video quảng cáo sản phẩm chuyên nghiệp.",
        ],
      },
      {
        category: "Camera cô gái từ trên xuống",
        prompts: [
          "Một hành lang căn hộ hiện đại, ánh sáng tự nhiên mềm mại, không gian sang trọng tối giản. Nhân vật: Một cô gái châu Á trẻ đẹp mặc váy đen ôm body, áo khoác tweed màu be, đội mũ nồi đen, đi bốt trắng cao cổ. Hành động: Camera bắt đầu từ góc nhìn trên cao nhìn xuống khuôn mặt cô gái, sau đó từ từ hạ thấp xuống ngang tầm mắt. Cô gái đứng yên tự tin, mắt nhìn theo camera, biểu cảm nhẹ nhàng cuốn hút.",
          "Video thời trang toàn thân của một cô gái trẻ đang tạo dáng trước gương, cô gái xoay nhẹ hông và vai sang hai bên trước gương. Camera cố định, bắt trọn chuyển động mềm mại của bộ trang phục. Video chất lượng cao, độ phân giải 4K",
          "Camera bắt đầu từ góc nhìn trên cao nhìn xuống khuôn mặt cô gái, sau đó từ từ hạ thấp xuống ngang tầm mắt. Cô gái đứng yên tự tin, mắt nhìn theo camera, biểu cảm nhẹ nhàng cuốn hút.",
          "Camera xoay vòng 360 độ xung quanh cô gái một cách mượt mà và điện ảnh. Cô gái đứng tạo dáng tự tin, tay hơi di chuyển nhẹ, tóc bay nhẹ tự nhiên. Quần áo chuyển động mềm mại chân thực theo chuyển động cơ thể. Hiệu ứng camera giống quay drone vòng quanh người mẫu.3 Camera từ từ bay lên cao trở lại góc nhìn từ trên xuống giống lúc đầu. Cô gái hơi ngẩng đầu nhìn theo camera. Chuyển động mượt mà, điện ảnh",
        ],
      },
    ],
  },
  {
    id: "thoi-trang-nam",
    title: "Video thời trang nam (ngắn 6-8s)",
    note: "Prompt tiếng Việt, dùng cho video AI người mẫu nam giới thiệu trang phục.",
    categories: [
      {
        category: "BƯỚC TỚI TRƯỚC TỰ TIN",
        prompts: [
          "“Tạo video dọc 9:16. Nhân vật nam bước tới trước tự tin, dáng người thẳng và nét mặt thoải mái. Camera giữ cố định và bắt trọn outfit khi nhân vật tiến gần.”",
          "“Nhân vật nam tiến về phía trước với phong thái tự tin, vai mở và bước đều. Camera giữ ổn định và làm rõ từng chi tiết trang phục.”",
          "“Cho nhân vật nam bước từ xa tới gần ống kính, giữ biểu cảm tự nhiên. Camera ghi lại toàn bộ chuyển động và outfit rõ nét.”",
          "“Nhân vật nam bước tới trước nhẹ nhàng, nhịp bước rõ ràng. Camera đứng yên, lấy toàn thân và giữ ánh sáng mềm mại.”",
          "“Tạo video 9:16. Nhân vật nam di chuyển về phía camera với sự tự tin và nụ cười nhẹ. Camera giữ ổn định để outfit rõ ràng.”",
        ],
      },
      {
        category: "XOAY NGƯỜI 360°",
        prompts: [
          "“Nhân vật nam xoay tròn 360° để khoe trọn form quần áo. Camera đứng im, giữ toàn thân trong khung hình.”",
          "“Tạo video 9:16. Nhân vật xoay một vòng chậm rãi để thể hiện từng góc trang phục. Camera không rung, giữ ánh sáng đều.”",
          "“Cho nhân vật nam xoay 360° với tốc độ tự nhiên, dừng lại ở mặt trước. Camera bắt rõ outfit từ đầu đến chân.”",
          "“Nhân vật xoay trọn vòng, từng góc được ghi lại rõ nét. Camera giữ độ cao cố định và ánh sáng mềm.”",
          "“Tạo video. Nhân vật nam xoay 360° chậm, giữ tư thế thẳng và phong thái lịch sự. Camera quay đứng yên.”",
        ],
      },
      {
        category: "CHỈNH ÁO, KÉO ÁO",
        prompts: [
          "“Nhân vật nam dùng hai tay chỉnh lại vạt áo nhẹ nhàng. Camera lấy cận thân trên, ánh sáng mềm.”",
          "“Cho nhân vật nam kéo nhẹ phần cổ áo để làm rõ chất liệu. Camera giữ cố định, không rung.”",
          "“Nhân vật nam dùng tay vuốt áo từ trên xuống để tạo sự phẳng phiu. Camera bắt nét rõ form áo.”",
          "“Tạo video 9:16. Nhân vật chỉnh tay áo, biểu cảm tự nhiên. Camera giữ ánh sáng đều.”",
          "“Nhân vật nam cầm vạt áo và kéo nhẹ để thể hiện độ co giãn. Camera lấy trung cảnh.”",
        ],
      },
      {
        category: "BỎ TAY VÀO TÚI QUẦN",
        prompts: [
          "“Nhân vật nam bước nhẹ và đưa một tay vào túi quần, phong thái tự nhiên. Camera ghi toàn thân.”",
          "“Tạo video 9:16. Nhân vật cho hai tay vào túi quần, đứng pose tự tin. Camera giữ cố định.”",
          "“Nhân vật nam thao tác cho tay vào túi quần rồi nhìn thẳng ống kính. Camera trung cảnh.”",
          "“Nhân vật nam bước một bước và cho tay vào túi quần, biểu cảm thoải mái. Camera giữ ánh sáng mềm.”",
          "“Cho nhân vật nam tạo dáng với hai tay trong túi quần. Camera đứng im, outfit rõ nét.”",
        ],
      },
      {
        category: "QUAY NHẸ 45° – 90° SANG TRÁI HOẶC PHẢI",
        prompts: [
          "“Nhân vật nam quay người 45° sang phải để khoe form áo. Camera giữ trung cảnh.”",
          "“Cho nhân vật nam xoay nhẹ 90° sang trái và giữ dáng vài giây. Camera rõ outfit.”",
          "“Nhân vật chuyển tư thế từ chính diện sang nghiêng 45°. Camera giữ ánh sáng đều.”",
          "“Tạo video 9:16. Nhân vật xoay người nhẹ sang phải để thể hiện đường may áo.”",
          "“Nhân vật nam xoay 90° sang trái rồi quay lại chính diện. Camera giữ nét, không rung.”",
        ],
      },
      {
        category: "GIƠ TAY CHÀO HOẶC VẪY NHẸ",
        prompts: [
          "“Nhân vật nam nhìn sang trái, sau đó quay lại nhìn camera. Camera trung cảnh.”",
          "“Nhân vật liếc nhẹ sang phải rồi nhìn lại ống kính. Camera giữ nét gương mặt.”",
          "“Tạo video 9:16. Nhân vật chuyển ánh mắt sang trái phải tự nhiên.”",
          "“Nhân vật nam quay đầu sang phải rồi trở lại chính diện. Camera ổn định.”",
          "“Cho nhân vật thực hiện động tác nhìn sang trái – phải và cuối cùng nhìn vào camera.”",
        ],
      },
      {
        category: "BƯỚC QUA CAMERA (ĐI NGANG KHUNG HÌNH)",
        prompts: [
          "“Nhân vật nam bước ngang qua khung hình từ trái sang phải. Camera đứng im.”",
          "“Tạo video. Nhân vật đi từ phải sang trái với dáng thẳng, outfit rõ.”",
          "“Nhân vật nam đi ngang khung hình với bước đều, phong thái tự tin.”",
          "“Nhân vật đi ngang qua ống kính chậm rãi để thể hiện form quần áo.”",
          "“Camera đứng im, nhân vật bước ngang và giữ ánh sáng mềm.”",
        ],
      },
      {
        category: "DỪNG LẠI VÀ POSE 2–3 TƯ THẾ",
        prompts: [
          "“Nhân vật nam dừng lại và tạo 2 tư thế pose tự tin. Camera ghi toàn thân.”",
          "“Nhân vật đứng yên và đổi 3 dáng pose nhẹ nhàng. Camera giữ nét outfit.”",
          "“Tạo video. Nhân vật chuyển đổi dáng đứng liên tục nhưng tự nhiên.”",
          "“Nhân vật nam dừng lại tạo dáng với tay trong túi rồi đổi sang khoanh tay.”",
          "“Nhân vật đứng pose 2–3 kiểu để làm rõ trang phục. Camera trung cảnh.”",
        ],
      },
    ],
  },
  {
    id: "gia-dinh",
    title: "Video gia đình phong cách Pixar",
    note: "Prompt tiếng Anh, phong cách hoạt hình 3D Disney/Pixar. Thay [Tên mẹ] và [Tên bé] bằng tên nhân vật bạn muốn trước khi dùng.",
    categories: [
      {
        category: "Trồng cây",
        prompts: [
          "Cinematic 3D animation, close-up of a mother [Tên mẹ] and her young daughter [Tên bé] kneeling in a sun-drenched garden, the girl [Tên bé] holding a small shovel digging into rich brown soil, mother [Tên mẹ] smiling encouragingly, vibrant green plants in background, soft bokeh, 8k resolution, high detail, Pixar aesthetic, no text, no logos, no watermark.",
          "3D Disney style, the little girl [Tên bé]'s small hands carefully holding a tiny green sprout over a hole in the dirt, the mother [Tên mẹ]'s hand gently guiding her, soft morning sunlight, extremely detailed textures of soil and leaves, consistent character design, 8k, no text, no logos, no watermark.",
          "3D animation, a magical moment where the girl [Tên bé] is watering plants with a cute blue watering can, sparkling water droplets caught in mid-air with sun refraction, mother [Tên mẹ] watching with a loving expression, vibrant garden colors, 8k, high-res, no text, no logos, no watermark.",
          "3D Disney/Pixar style, the little girl [Tên bé] proudly holding a large ripe red tomato she just picked, mother [Tên mẹ] smiling in the background, lush green garden background, golden hour lighting, 8k, cinematic, no text, no logos, no watermark.",
          "3D animation, emotional close-up, the little girl [Tên bé] with eyes closed smelling a vibrant pink flower, peaceful expression, mother [Tên mẹ]'s arm around her shoulder, soft warm lighting, high-resolution textures, 8k, no text, no logos, no watermark.",
          "3D Pixar style, close-up of a cute girl [Tên bé] with pigtails holding a small toy trowel, mother [Tên mẹ] in a gardening apron smiling in sunlit garden, rich brown soil and green leaves background, warm cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, focus on girl [Tên bé]'s small hand dropping brown seeds from her palm into a small dirt hole, mother [Tên mẹ] holds a seed packet looking on proudly, garden background with blurred flowers, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, girl [Tên bé] holding an elephant watering can pouring sparkling water onto a chậu cây, mother [Tên mẹ]'s hand points gently, vibrant green plants and sunlight background, joyful faces, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, girl [Tên bé] with pigtails carefully plucking a vibrant pink flower, mother [Tên mẹ] looking on with surprise and joy, warm sun rays hitting the garden flowers, colorful and happy scene, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, mother [Tên mẹ] and daughter [Tên bé] with pigtails closing their eyes and deeply inhaling the scent of a pink flower held between them, joyful smiles, sunlit garden flowers background, soft warm lighting, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Đi siêu thị",
        prompts: [
          "3D Pixar style animation, a little girl [Tên bé] happily pushing a small colorful shopping cart down a supermarket aisle filled with bright cereal boxes, her mother [Tên mẹ] walking beside her, cinematic lighting, vibrant colors, 8k, no text, no logos, no watermark.",
          "3D Disney style, close-up of the little girl [Tên bé] with a thoughtful expression choosing a bright red apple from a wooden crate at the supermarket, mother [Tên mẹ]'s hand on her shoulder, soft focus background, 8k, consistent character design, no text, no logos, no watermark.",
          "3D animation, the little girl [Tên bé] carefully putting a shiny red apple into her small shopping cart, detailed textures of the fruit and the metal cart, bright supermarket interior, Pixar aesthetic, 8k, no text, no logos, no watermark.",
          "3D Pixar style, the little girl [Tên bé] standing on her tiptoes to see the digital screen of a weighing scale as she weighs a bag of apples, mother [Tên mẹ] watching with a smile, high detail, cinematic lighting, 8k, no text, no logos, no watermark.",
          "3D Disney style, heart-warming moment at the supermarket checkout, the little girl [Tên bé] handing a bill to the cashier with a proud smile, mother [Tên mẹ] looking on with love, realistic textures, 8k resolution, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Vẽ tranh",
        prompts: [
          "3D Pixar style, close-up of a cute girl [Tên bé] with curly hair and her young mother [Tên mẹ] leaning over a canvas, the girl [Tên bé] is holding a pencil to draw, bright curious eyes, warm indoor lighting, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, the girl [Tên bé] and her mother [Tên mẹ] looking at a colorful paint palette, the girl [Tên bé] is dipping a brush into a jar of water, water splashing slightly, vivid colors, expressive faces, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, side view of the mother [Tên mẹ] and daughter [Tên bé], the daughter [Tên bé] is painting a bright yellow sun on a canvas, the mother [Tên mẹ] is smiling and touching her shoulder, vibrant colors, messy paint on hands, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, close-up of the girl [Tên bé]'s hand with green paint on her finger pressing onto paper, her mother [Tên mẹ] laughing in the background, joyful atmosphere, high detail, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, the mother [Tên mẹ] and daughter [Tên bé] hugging, holding up a colorful completed drawing of a sun and flowers, triumphant and happy expressions, soft warm lighting, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Trước khi ngủ",
        prompts: [
          "Cinematic 3D animation, mother [Tên mẹ] and daughter [Tên bé] sitting on a bed reading a large glow-in-the-dark book, warm golden bedroom lighting, Pixar aesthetic, 8k, high detail, cozy atmosphere, no text, no logos, no watermark.",
          "3D Disney style, extremely cute close-up of the little girl [Tên bé] wearing cloud pajamas letting out a big yawn, eyes watering slightly, mother [Tên mẹ]'s hand gently touching her cheek, soft bokeh, 8k, no text, no logos, no watermark.",
          "3D animation, the little girl [Tên bé]'s hand pressing a vintage lamp switch, the moment the light changes to a warm dim glow, consistent character design, cozy bedroom background, 8k, no text, no logos, no watermark.",
          "3D Pixar style, heart-warming shot of the mother [Tên mẹ] tucking a thick patterned blanket around her daughter [Tên bé], the girl [Tên bé] looking up with sleepy happy eyes, realistic fabric textures, 8k, cinematic lighting, no text, no logos, no watermark.",
          "3D Disney style, a tender moment of a mother [Tên mẹ] kissing her daughter [Tên bé]'s forehead as she falls asleep, soft moonlight shadows, peaceful facial expressions, high resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Chăm sóc thú cưng",
        prompts: [
          "Cinematic 3D animation, a little girl [Tên bé] and her mother [Tên mẹ] sitting on a living room rug, the girl [Tên bé] gently brushing a fluffy golden retriever puppy, Pixar aesthetic, soft sunlight, 8k resolution, high detail, no text, no logos, no watermark.",
          "3D Disney style, close-up of the little girl [Tên bé]'s hands placing a small blue bowl of food in front of a happy puppy, mother [Tên mẹ] smiling in the background, vibrant colors, consistent character design, 8k, no text, no logos, no watermark.",
          "3D animation, the little girl [Tên bé] throwing a bright red ball in a lush green backyard, a golden puppy running excitedly, frozen motion, cinematic lighting, 8k, Pixar style, no text, no logos, no watermark.",
          "3D Pixar style, a tender moment of the little girl [Tên bé] petting the puppy's head, the puppy looking up with large expressive eyes, detailed fur textures, warm afternoon sun, 8k, no text, no logos, no watermark.",
          "3D Disney style, heart-warming final shot of the little girl [Tên bé] giving the puppy a big hug, mother [Tên mẹ] leaning in to join the embrace, beautiful garden background, emotional expressions, 8k, high-res, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Đi tắm",
        prompts: [
          "3D Pixar style, close-up of a cute girl [Tên bé] in a bubble bath wearing a ducky cap, mother [Tên mẹ] laughing as water splashes, iridescent bubbles everywhere, bright bathroom, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, girl [Tên bé] holding a pink sponge with thick white foam, mother [Tên mẹ] looking on encouragingly, soft bubbles on skin, cozy bathroom background, expressive joyful faces, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, mom [Tên mẹ] using a small showerhead to rinse clear water over daughter [Tên bé]'s shoulders, foam washing away, sparkling water droplets, peaceful and happy scene, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, girl [Tên bé] wrapped in a giant fluffy white towel with a bear hood, mother [Tên mẹ] hugging her warmly, soft textures, warm indoor lighting, intimate mother-daughter moment, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, mother [Tên mẹ] putting lotion on girl [Tên bé]'s cheek, girl [Tên bé] rubbing lotion on her hands, rosy cheeks, bright eyes, soft skin texture, warm domestic atmosphere, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Màu sắc",
        prompts: [
          "3D Pixar style, close-up of a cute girl [Tên bé] in a floral dress touching lush green grass in a sunlit park, mother [Tên mẹ] smiling in the background, vibrant natural colors, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, girl [Tên bé] with wide curious eyes pointing at a bright red rose bush, mother [Tên mẹ] kneeling beside her, soft sunlight filtering through leaves, vivid red petals, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, girl [Tên bé] sliding down a bright yellow slide, mother [Tên mẹ] waiting at the bottom with open arms, joyful expressions, motion blur on the slide, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, mother [Tên mẹ] and daughter [Tên bé] sitting on a bench looking up at a vast clear blue sky, fluffy white clouds, peaceful and happy atmosphere, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, girl [Tên bé] running with a bunch of multi-colored balloons (red, blue, yellow, green), mother [Tên mẹ] laughing and spinning, colorful park background, celebration of colors, cinematic lighting, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Bốn mùa",
        prompts: [
          "3D Disney style, close-up of a pink flower blooming in a spring garden, the little girl [Tên bé] and mother [Tên mẹ] looking on with wonder, soft cinematic lighting, 8k, vibrant colors, no text, no logos, no watermark.",
          "3D animation, the little girl [Tên bé] wearing a sun hat splashing happily in a bright blue kiddie pool, sun refractions in the water, summer vibes, Pixar aesthetic, 8k, high detail, no text, no logos, no watermark.",
          "3D Pixar style, the little girl [Tên bé] jumping into a giant pile of orange and yellow autumn leaves, mother [Tên mẹ] smiling in the background, golden hour lighting, realistic leaf textures, 8k, no text, no logos, no watermark.",
          "3D Disney style, heart-warming shot of the mother [Tên mẹ] and daughter [Tên bé] in heavy winter clothes standing in a snowy forest, the girl [Tên bé] shivering cutely, soft blue winter light, 8k resolution, no text, no logos, no watermark.",
          "3D animation, final scene showing the girl [Tên bé] and mother [Tên mẹ] holding a colorful chart of the four seasons, consistent character design, bright indoor lighting, high-quality textures, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Làm bánh",
        prompts: [
          "3D Pixar style, cinematic lighting, a close-up of mother [Tên mẹ] and a little girl [Tên bé] with curly hair, both looking down at a ceramic bowl with expressions of excitement and focus as an egg is being cracked, vibrant colors, 8k, high-resolution, no text, no logos, no watermark.",
          "3D Pixar style, a little girl [Tên bé] with a smudge of white flour on her nose laughing, her mother [Tên mẹ] smiling beside her, a bowl of flour on a wooden table, soft bokeh background, 8k, cinematic lighting, no text, no logos, no watermark.",
          "3D Pixar style, full shot of mother [Tên mẹ] and daughter [Tên bé] in aprons, hands deep in a large piece of dough on a rustic wooden table, determined and happy facial expressions, warm kitchen atmosphere, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a little girl [Tên bé] sitting on the kitchen floor looking into the glowing orange light of an oven, reflection of cookies in her eyes, mother [Tên mẹ] standing behind her with oven mits, magical atmosphere, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a close-up of a happy little girl [Tên bé] biting into a delicious chocolate chip cookie, her mother [Tên mẹ] hugging her from the side, a glass of milk on the table, warm and joyful emotion, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Vệ sinh buổi sáng",
        prompts: [
          "3D Disney style animation, a close-up of a cute girl [Tên bé] brushing her teeth with white foam, her mother [Tên mẹ] standing behind her with a loving expression, bright bathroom background, cinematic lighting, vibrant colors, 8k, high-resolution, no text, no logos, no watermark.",
          "3D animation, the little girl [Tên bé] with a fresh face and water droplets on her skin, holding a fluffy white towel, her mother [Tên mẹ] smiling in the background, soft morning sunlight through the window, 8k, cinematic, no text, no logos, no watermark.",
          "3D Pixar style, the little girl [Tên bé] looking in a mirror while combing her curly hair, her mother [Tên mẹ] putting a bow on her head, warm indoor lighting, sparkling details, high-resolution, 8k, no text, no logos, no watermark.",
          "3D animation, the cute girl [Tên bé] twirling in her new floral dress, fabric flowing, mother [Tên mẹ] clapping in the background, cozy bedroom atmosphere, 8k, high-quality render, no text, no logos, no watermark.",
          "3D Disney style, a heartwarming shot of the mother [Tên mẹ] and daughter [Tên bé] hugging and smiling brightly at the camera, sunlight glowing behind them, 8k, ultra-detailed, cinematic lighting, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Dọn dẹp đồ chơi",
        prompts: [
          "3D Pixar style, cinematic lighting, a close-up of a little curly-haired girl [Tên bé] in a pink sweater holding a big basket, a cluttered child's bedroom full of colorful toys in the background, focused expression, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a little curly-haired girl [Tên bé] with dirt-stained cheeks smiling while placing a book on a bookshelf, her mother [Tên mẹ] kneeling beside her, soft golden hour lighting, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a little curly-haired girl [Tên bé] laughing as she puts a teddy bear in one plastic bin and a toy car in another bin, mother [Tên mẹ] in the background, lush child's bedroom setting, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a mother [Tên mẹ] and curly-haired daughter [Tên bé] standing side by side in the child's bedroom, measuring their height against a tall blooming sunflower decal on the wall, bright and joyful atmosphere, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a close-up of a little curly-haired girl [Tên bé]'s hand with dirt-stained fingers, mother [Tên mẹ] nearby, beaming with pride, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Chơi đất nặn",
        prompts: [
          "3D Pixar style, cinematic lighting, a close-up of a little curly-haired girl [Tên bé] in a striped shirt holding colorful clay bars, her young mother [Tên mẹ] beside her, focused expression, cozy playroom background, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a close-up of a little girl [Tên bé]'s hands making a perfectly round red clay ball, mother [Tên mẹ] watching, colorful clay tools on a wooden table, soft bokeh background, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a little curly-haired girl [Tên bé] laughing while pressing her thumb onto a blue clay ball on a messy art table, mother [Tên mẹ] smiling, magical playroom atmosphere, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a mother [Tên mẹ] and curly-haired daughter [Tên bé] sitting side by side at a wooden art table, carefully shaping tiny clay animals, colorful clay pieces everywhere, bright and joyful, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a close-up of a finished colorful clay turtle with detailed shell and eyes, being held by a proud little girl [Tên bé] with dirt-stained fingers, mother [Tên mẹ] looking on, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Cắm trại",
        prompts: [
          "3D Disney style animation, mother [Tên mẹ] and daughter [Tên bé] together lifting a bright blue camping tent on a lush green field, twilight sky, 8k, cinematic lighting, high-resolution, no text, no logos, no watermark.",
          "3D animation, a close-up of a little girl [Tên bé]'s face illuminated by the warm orange glow of a campfire, mother [Tên mẹ] in the background, starry night sky, 8k, ultra-detailed, no text, no logos, no watermark.",
          "3D Pixar style, a cute girl [Tên bé] holding a toasted marshmallow on a stick, campfire sparks in the air, mother [Tên mẹ] smiling beside her, cozy camping vibe, 8k, vibrant colors, no text, no logos, no watermark.",
          "3D animation, wide shot from above of mother [Tên mẹ] and daughter [Tên bé] lying on grass looking up at a spectacular Milky Way galaxy sky, magical atmosphere, 8k, high-resolution, no text, no logos, no watermark.",
          "3D Disney style, the little girl [Tên bé] sleeping peacefully inside a glowing tent, hugging a teddy bear, mother [Tên mẹ] watching her with love, soft warm lantern light, 8k, cinematic, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Tập thể dục buổi sáng",
        prompts: [
          "3D Pixar style, cinematic lighting, a close-up of a little girl [Tên bé] in a tracksuit stretching her arms high, mother [Tên mẹ] nearby, bright sunny balcony background with plants, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a little girl [Tên bé] with bouncing pigtails hopping on one leg over colorful mats, her mother [Tên mẹ] smiling and cheering her on, soft morning glow, 8k, no text, no logos, no watermark.",
          "3D Pixar style, action shot of a little girl [Tên bé] twisting her body with hands on hips, mother [Tên mẹ] in the setting, a playful and energetic morning exercise setting, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a mother [Tên mẹ] and daughter [Tên bé] running on the spot together on yoga mats, focus on their happy and determined faces, bright and airy room, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a close-up of a little girl [Tên bé] with closed eyes and a peaceful smile, taking a deep breath, her mother [Tên mẹ]'s hand gently on her shoulder, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Đọc sách",
        prompts: [
          "3D Pixar style, cinematic lighting, a close-up of a little curly-haired girl [Tên bé] in pajamas looking at a colorful bookshelf with her mother [Tên mẹ], warm and cozy atmosphere, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a little girl [Tên bé] sitting on her mother [Tên mẹ]'s lap, her tiny hand turning the page of a large picture book, warm golden light, soft bokeh, 8k, no text, no logos, no watermark.",
          "3D Pixar style, action shot of a little girl [Tên bé]'s finger pointing at a bright yellow star in a storybook, mother [Tên mẹ] beside her, sparkling eyes and focused expression, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a mother [Tên mẹ] and curly-haired daughter [Tên bé] leaning their heads together while reading a book, focus on their joyful faces, cozy bedroom setting, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a close-up of a little girl [Tên bé] fast asleep in her mother [Tên mẹ]'s arms, clutching a blue book, peaceful facial expression, soft moonlight, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Đi biển",
        prompts: [
          "3D Disney style animation, a close-up of a cute girl [Tên bé] digging a hole in the white sand with a yellow shovel, mother [Tên mẹ] in the background, sunlit beach background, 8k, cinematic lighting, no text, no logos, no watermark.",
          "3D animation, the girl [Tên bé] and her mother [Tên mẹ] sitting by a large sandcastle with a red flag, vibrant blue ocean in the background, high-resolution, 8k, no text, no logos, no watermark.",
          "3D Pixar style, the girl [Tên bé] holding a beautiful pink seashell up to the sun, sparkling water reflections, mother [Tên mẹ] smiling in the background, 8k, ultra-detailed, no text, no logos, no watermark.",
          "3D animation, a joyful shot of the girl [Tên bé] splashing water with a big smile, mother [Tên mẹ] nearby, water droplets frozen in mid-air, bright summer sunlight, 8k, cinematic, no text, no logos, no watermark.",
          "3D Disney style, the little girl [Tên bé] relaxing on a watermelon swim ring floating on turquoise sea water, mother [Tên mẹ] watching from the shore, peaceful expression, cinematic lighting, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Chơi đồ chơi",
        prompts: [
          "3D Disney style animation, a close-up of a cute girl [Tên bé]'s hands carefully stacking colorful wooden blocks into a high tower, mother [Tên mẹ] watching, soft sunlight, 8k, cinematic lighting, no text, no logos, no watermark.",
          "3D animation, the girl [Tên bé] watching a colorful spinning top with wide, amazed eyes, mother [Tên mẹ] showing her, blurred motion of the toy, cozy playroom background, 8k, ultra-detailed, no text, no logos, no watermark.",
          "3D Pixar style, a dynamic shot of the girl [Tên bé] bouncing a large starry ball, the ball caught mid-air, mother [Tên mẹ] laughing in the background, 8k, high-resolution, no text, no logos, no watermark.",
          "3D animation, the little girl [Tên bé] peeking from behind a white curtain with a mischievous smile, mother [Tên mẹ] looking for her, eyes sparkling, soft interior lighting, 8k, cinematic, no text, no logos, no watermark.",
          "3D Disney style, the heartwarming moment the mother [Tên mẹ] finds the girl [Tên bé] behind the curtain, both hugging and laughing, bright and happy colors, 8k, high-quality render, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Đi sở thú",
        prompts: [
          "3D Pixar style, cinematic lighting, a close-up of a little girl [Tên bé] looking up with wide eyes at a giraffe's head, mother [Tên mẹ] beside her, vibrant zoo background with sunlight filtering through leaves, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a little girl [Tên bé] with a big smile holding a green branch out to a gentle giraffe, her mother [Tên mẹ] encouraging her from behind, soft warm lighting, 8k, no text, no logos, no watermark.",
          "3D Pixar style, action shot of a little girl [Tên bé] hopping and making funny faces in front of a monkey enclosure, mother [Tên mẹ] laughing, monkeys in the background, joyful atmosphere, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a little girl [Tên bé] waving her hand at a large grey elephant with its trunk raised, mother [Tên mẹ] by her side, a bright and colorful zoo setting, 8k, no text, no logos, no watermark.",
          "3D Pixar style, a mother [Tên mẹ] and daughter [Tên bé] taking a selfie together, smiling faces, zoo entrance with an \"ABC ZOO\" sign in the background, high-resolution, 8k, no text, no logos, no watermark.",
        ],
      },
      {
        category: "Nhạc cụ",
        prompts: [
          "3D Disney style animation, a close-up of a cute girl [Tên bé]’s hands strumbling a small blue ukulele, mother [Tên mẹ] listening, musical notes floating in the air, colorful playroom background, 8k, cinematic lighting, no text, no logos, no watermark.",
          "3D animation, a dynamic shot of the girl [Tên bé] beating a toy drum with dynamic musical notes flying around, mother [Tên mẹ] dancing in the background, 8k, ultra-detailed, no text, no logos, no watermark.",
          "3D Pixar style, close-up of the girl [Tên bé] with puffed cheeks blowing into a yellow recorder, mother [Tên mẹ] listening, focused expression, heart-shaped musical notes, 8k, magical lighting, no text, no logos, no watermark.",
          "3D animation, the girl [Tên bé] and her mother [Tên mẹ] listening to a spinning music box, warm and peaceful atmosphere, instruments around them, 8k, high-resolution, no text, no logos, no watermark.",
          "3D Disney style, a heartwarming shot of the mother [Tên mẹ] and daughter [Tên bé] hugging and dancing together amidst a burst of colorful musical notes, radiant expressions, 8k, high-quality render, no text, no logos, no watermark.",
        ],
      },
    ],
  },
];

export const videoPromptsCount = videoPromptGroups.reduce(
  (sum, g) => sum + g.categories.reduce((s, c) => s + c.prompts.length, 0),
  0
);
